Repository SER515Team13/NumberNinja, pull requests merged in 2019-11, with the labels that each got.

#17 Us14 view questions student
  NumberNinjaClient/src/app/app.module.ts
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.css
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.html
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.spec.ts
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.ts
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.css
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.html
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.spec.ts
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.ts
  NumberNinjaClient/src/app/student/model/assignment.spec.ts
  NumberNinjaClient/src/app/student/model/assignment.ts
  NumberNinjaClient/src/app/student/model/question.spec.ts
  NumberNinjaClient/src/app/student/model/question.ts
  NumberNinjaClient/src/app/student/questions/view-questions/view-questions.component.css
  NumberNinjaClient/src/app/student/questions/view-questions/view-questions.component.html
  NumberNinjaClient/src/app/student/questions/view-questions/view-questions.component.spec.ts
  NumberNinjaClient/src/app/student/questions/view-questions/view-questions.component.ts
  NumberNinjaClient/src/app/student/service/assignment-service.service.spec.ts
  NumberNinjaClient/src/app/student/service/assignment-service.service.ts
  NumberNinjaClient/src/app/student/service/question-service.service.spec.ts
  NumberNinjaClient/src/app/student/service/question-service.service.ts
  NumberNinjaServer/package.json
Labels: dependencies

#18 US13 - View assignment with details - for student
  NumberNinjaClient/src/app/routes.ts
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.html
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.spec.ts
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.ts
  NumberNinjaClient/src/app/student/model/assignment.spec.ts
  NumberNinjaClient/src/app/student/model/assignment.ts
  NumberNinjaClient/src/app/student/service/assignment-service.service.spec.ts
  NumberNinjaClient/src/app/student/service/assignment-service.service.ts
  NumberNinjaClient/src/app/student/student.component.html
  NumberNinjaClient/src/app/student/student.component.spec.ts
  NumberNinjaClient/src/app/toolbars/studenttoolbar/studenttoolbar.component.html
  NumberNinjaClient/src/app/user/signin/signin.component.ts
  NumberNinjaServer/models/assignment.js
  NumberNinjaServer/models/student-assignment.js
  NumberNinjaServer/routes/assignments.js
  NumberNinjaServer/routes/users.js
Labels: enhancement

#24 Us14 view questions student
  NumberNinjaClient/src/app/routes.ts
  NumberNinjaClient/src/app/student/assignments/view-assignments/view-assignments.component.html
  NumberNinjaClient/src/app/student/questions/view-questions/view-questions.component.html
  NumberNinjaClient/src/app/student/questions/view-questions/view-questions.component.spec.ts
  NumberNinjaClient/src/app/student/questions/view-questions/view-questions.component.ts
  NumberNinjaClient/src/app/student/service/question-service.service.ts
Labels: enhancement

#25 Us9 add question
  NumberNinjaClient/src/app/app.module.ts
  NumberNinjaClient/src/app/teacher/model/question.ts
  NumberNinjaClient/src/app/teacher/question/question.component.css
  NumberNinjaClient/src/app/teacher/question/question.component.html
  NumberNinjaClient/src/app/teacher/question/question.component.ts
  NumberNinjaClient/src/app/teacher/service/question-service.ts
  NumberNinjaClient/src/app/user/signup/signup.component.ts
  NumberNinjaServer/models/question.js
  NumberNinjaServer/routes/questions.js
  NumberNinjaServer/routes/users.js
Labels: enhancement

#32 Us15 solve questions and submit part 2
  NumberNinjaClient/src/app/shared/mathparser.service.spec.ts
  NumberNinjaClient/src/app/shared/mathparser.service.ts
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.html
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.ts
  NumberNinjaClient/src/app/teacher/service/question-service.ts
  NumberNinjaClient/src/app/toolbars/studenttoolbar/studenttoolbar.component.ts
  NumberNinjaServer/routes/questions.js
  package-lock.json
Labels: enhancement

#40 Added routing to question page when submitted solution is correct.
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.html
Labels: bug

#46 Implemented Find The Answer question type, toolbar generation accordi…
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.html
  NumberNinjaClient/src/app/student/canvas/solve-question/solve-question.component.ts
  NumberNinjaClient/src/app/student/service/question-service.service.ts
  NumberNinjaServer/models/studentAssignmentQuestion.js
  NumberNinjaServer/routes/questions.js
Labels: enhancement
